import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Long Island</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <nav className={styles.navDesktop}>
          <div className="container">
            <div className={styles.flex}>
              <div className={styles.left}>
                <Link href="/">
                  <div className={styles.logo}>
                    <Image
                      src="/img/logo_2.png"
                      alt="island"
                      className={styles.logoImg}
                      width={1612}
                      height={213}
                    />
                  </div>
                </Link>
              </div>
              <div className={styles.right}>
                <div className={styles.link}>NOSOTROS</div>
                <div className={styles.link}>SERVICIOS</div>
                <div className={styles.link}>NUESTRO CAMINO</div>
                <div className={styles.link}>CONTÁCTANOS</div>
              </div>
            </div>
          </div>
        </nav>
        <div className={styles.header}>
          <div className="container">
            <div className={styles.headerBox}>
              <div className={styles.left}>
                <div className={styles.title}>
                  <h1>
                    Somos una agencia creativa, digital y de marketing que
                    colabora con clientes de México, Estados Unidos y Canada.
                  </h1>
                </div>
                <div className={styles.text}>
                  <p>
                    Trabajamos de la mano con empresas que buscan llevar su
                    marca al siguiente nivel, con un enfoque orientado a
                    objetivos, crecimiento e impacto en las audiencias.
                  </p>
                  <p>
                    Vemos la comunicación de marca como un todo; desde la
                    concepción de la estrategia, creatividad y ejecución de la
                    misma.
                  </p>
                  <p>
                    Long Island, al ser una agencia boutique, brinda servicio
                    personalizado cuidando los intereses y objetivos de cada uno
                    de sus clientes. Buscamos relaciones a largo plazo que nos
                    permitan crecer en conjunto.
                  </p>
                </div>
              </div>
              <div className={styles.right}>
                <div className={styles.image}>
                  <Image
                    src="/img/nosotros.jpg"
                    alt="island"
                    className={styles.imageImg}
                    width={2000}
                    height={1336}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
        <section className={styles.servicios}>
          <div className={styles.bg} />
          <div className={styles.overlay} />
          <div className={styles.content}>
            <div className="container">
              <div className={styles.text}>
                <h4>Creatividad</h4>
                <h4>Identidad de marca</h4>
                <h4>Artes finales y adaptaciones</h4>
                <h4>Páginas web</h4>
                <h4>Eventos Multimedia</h4>
                <h4> Planificación y compra de medios offline y online</h4>
              </div>
            </div>
          </div>
        </section>
        <div className={styles.home}>
          <div className="container">
            <div className={styles.title}>NUESTRO CAMINO</div>
            <div className={styles.clientes}>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-1.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-2.svg.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-3.svg.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-4.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-5.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-6.svg.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-7.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-8.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-9.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-10.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-11.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-12.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-13.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-14.svg.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-15.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-16.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-17.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-18.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-19.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
              <div className={styles.cliente}>
                <Image
                  src="/img/client-20.jpg"
                  alt="island"
                  className={styles.logoImg}
                  width={1000}
                  height={600}
                />
              </div>
            </div>
          </div>
        </div>
        <div className={styles.contacto}>
          <div className="container">
            <div className={styles.contactanos}>
              <div className={styles.left}>
                <Image
                  src="/img/contacto.png"
                  alt="island"
                  className={styles.logoImg}
                  width={1612}
                  height={213}
                />
              </div>
              <div className={styles.right}>
                <div className={styles.form}>
                  <label>Nombre</label>
                  <input type="text" name="name" placeholder="Nombre" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
